export * from "./edit";
export * from "./home";
export * from "./homeCreate";
export * from "./formulario_registro";
export * from "./fornulario_ingreso";
export * from "./formulario_datos";
export * from "./formulario_video";
export * from "./formulario_trabajo/area";
export * from "./Empleos/Descripcion";